
#' Emissions by Energy Type
#'
#' This function determines the emissions generated by energy consumption of a given energy type
#' @param energy consumption - default = annual (kWh)
#' @param emissions_factor for the energy source (tons of CO2 per kWh)
#' @param time_frame period of energy use (default = years)
#' @return total emissions - default = CO2 (tons of CO2)
#'
# function definition

emissions = function(energy, emissions_factor, time_frame) {
  # here's where I add error checking
  time_frame = ifelse(time_frame < 0,return("time must be greater than zero"), time_frame)
  # here's where I calculate emissions
  result = energy * emissions_factor * time_frame
  return(result)
  }

